import KEYS from './resources.keys';

const RESOURCES = {
  it: {
    "account": "io",
    "back": "indietro",
    "Cancel": "Annulla",
    "Calendar": "Calendario attività gruppi",
    "Close the session": "Chiudi la sessione",
    "create": "crea",
    "Day": "Giorno",
    "Debug mode": "Modalità debug",
    "destination": "destinazione",
    "End time": "Fine",
    "Go home": "Vai alla pagina iniziale",
    "Group": "Gruppo",
    "Groups": "Gruppi",
    "helps you organize daily shuttles": "aiuta a gestire navette giornaliere",
    "insert key": "chiave d'accesso",
    "is driver": "guidatore",
    "Leave session": "Abbandona la sessione",
    "loading session...": "caricamento sessione...",
    "login": "accedi",
    "management": "gestione dati",
    "Management Access": "Accesso Gestione",
    "modify item": "modifica elemento",
    "new item": "nuovo elemento",
    "none": "nessuno",
    "Person": "Soggetto",
    "Persons": "Soggetti",
    "remove item": "elimina elemento",
    "remove person": "elimina persona",
    "Restore default settings": "Ripristina le opzioni iniziali",
    "session name": "nome della sessione",
    "session not accessible": "sessione non accessibile",
    "Session settings": "Impostazioni",
    "Session shuttles": "Navette",
    "Share the session": "Condividi sessione",
    "Show infos": "Mostra informazioni aggiuntive",
    "Start time": "Inizio",
    "Switch to dark theme": "Passa al tema scuro",
    "Switch to light theme": "Passa al tema chiaro",
    "Type access code\nor create new session": "digita un codice\no crea una nuova sessione",
    "undefined": "non definito",
    "Welcome!": "Benvenuto!",
    "what you need to know": "cosa devi sapere",
    "your name is undefined": "scegliere un nome valido",
    "sunday": "domenica",
    "monday": "lunedì",
    "tuesday": "martedì",
    "wednesday": "mercoledì",
    "thursday": "giovedì",
    "friday": "venerdì",
    "saturday": "sabato",
    "january": "gennaio",
    "february": "febbraio",
    "march": "marzo",
    "april": "aprile",
    "may": "maggio",
    "june": "giugno",
    "july": "luglio",
    "august": "agosto",
    "september": "settembre",
    "october": "ottobre",
    "november": "novembre",
    "december": "dicembre",
    [KEYS._session_back_home]: "ritorno",
    [KEYS._session_configure]: "configurazione",
    [KEYS._session_to_destination]: "andata",
    [KEYS._welcome_line_first]: "Questa applicazione ti aiuterà a definire le navette necessarie al trasporto dei soggetti interessati.",
    [KEYS._welcome_line_second]: "Puoi lavorare alla giornata con organizzazioni estemporanee oppure definire un programma settimanale di attività e un elenco di persone ricorrente.",
    [KEYS._info_area_code]: "Ogni sessione è pubblica identificata da un codice di 9 caratteri alfanumerici (testo e numero) divisi in tre gruppi",
    [KEYS._info_area_duration]: "La sessione viene automaticamente eliminata dopo 3 mesi dall'ultimo utilizzo",
    [KEYS._info_area_encryption]: "I contenuti di una sessione sono protetti dalla crittografia standard e sono leggibili solo da chi conosce il codice sessione",
    [KEYS._info_area_privacy]: "Non inserire mai informazioni sensibili nei messaggi e nelle note editabili poiché potrebbero essere letti da chiunque sia in possesso del codice di sessione",
    [KEYS._info_area_security]: "Fai in modo che nessun utente sia identificabile ed i nomi inseriti siano comprensibili solo agli utenti stessi",
    [KEYS._info_area_sharing]: "Condividendo il codice di fatto si condividono tutti i dati presenti nella sessione compresi i messaggi scambiati tra gli utenti",
    [KEYS._day_clear]: "cancella informazioni",
    [KEYS._day_clear_clipboard]: "cancella appunti",
    [KEYS._day_copy]: "copia informazioni",
    [KEYS._day_paste]: "incolla informazioni",
    [KEYS._day_edit]: "modifica informazioni",
    [KEYS._person_driver]: "guidatore",
    [KEYS._person_passenger]: "passeggero",
    [KEYS._person_mixed]: "guidatore o passeggero",
    [KEYS._no_shuttle_on_day]: "per questo giorno non è neccessaria alcuna navetta",
    [KEYS._add_shuttle_always]: "aggiungi comunque una navetta",
    [KEYS._my_name_title]: "il mio nome nei messaggi"
  }
}
export default RESOURCES;
